import { Language, Translation } from './types';

export const TRANSLATIONS: Record<Language, Translation> = {
  [Language.EN]: {
    nav: { home: 'Home', releases: 'Releases', download: 'Download', features: 'Features', terms: 'Terms', docs: 'Docs' },
    hero: { new_version: 'v2.0 Now Available', tagline: 'Intelligent Activity Tracker', subtext: 'Privacy-focused activity tracking. Understand how you spend your time with detailed analytics and local-only data storage.', cta_download: 'Download Now', cta_github: 'View Source', built_for: 'Built for Performance', powered_by: 'Powered by Modern Technologies' },
    features: { title: 'Why TimiGS?', realtime_title: 'Real-time Tracking', realtime_desc: 'Automatically detects active windows and tracks usage duration.', privacy_title: 'Privacy First', privacy_desc: 'All data is stored locally in SQLite. No cloud uploads.', analytics_title: 'Analytics & Charts', analytics_desc: 'Visualize data with beautiful Donut, Pie, and Bar charts.', timeline_title: 'Timeline View', timeline_desc: 'Browse activity history day-by-day with granular details.', crossplatform_title: 'Cross-Platform', crossplatform_desc: 'Built with Tauri v2 for high performance on Windows, Linux, and macOS.', i18n_title: 'Multilingual', i18n_desc: 'Fully localized interface supporting multiple global languages.' },
    downloads: { title: 'Download TimiGS', subtitle: 'Choose the version for your operating system.', latest_version: 'Latest Version', windows: 'Windows', windows_desc: 'Native 64-bit installers for Windows 10 and 11. Choose .exe for standard installation.', mac: 'macOS', mac_desc: 'Optimized for macOS. Supports Intel and Apple Silicon chips via universal binaries.', linux: 'Linux', linux_desc: 'Packages for major distributions. AppImage for universal compatibility, RPM for Fedora, and DEB for Ubuntu/Debian.', source: 'Source Code', source_title: 'Source Code & Other Assets', source_desc: 'Need access to source code tarballs, checksums, or older releases? Visit the full release page on GitHub.', installer_label: 'Installer', no_assets: 'No assets found.', loading: 'Loading releases...', error: 'Failed to load releases.', no_assets_platform: 'No assets available for this platform' },
    releases: { title: 'Release Notes', subtitle: 'Explore the evolution of TimiGS.', published_on: 'Published on', view_on_github: 'View on GitHub', assets: 'Assets', latest_badge: 'LATEST RELEASE', prerelease_badge: 'Pre-release' },
    terms: { title: 'Terms & Privacy', privacy_title: 'Privacy Policy', privacy_content: 'TimiGS is designed with privacy as a core value. All data collected by the application regarding your activity is stored strictly locally on your device using an encrypted SQLite database. We do not transmit your personal data to any external cloud servers.', data_title: 'Data Ownership', data_content: 'You own your data. You have full control to export, delete, or modify your local database at any time. TimiGS provides tools within the application to manage your data retention policies.', license_title: 'License', license_content: 'TimiGS is open-source software provided under the MIT License. You are free to use, modify, and distribute this software in accordance with the license terms.' },
    footer: { rights: 'All rights reserved.', created_by: 'Created by', built_with: 'Built with Tauri, Rust & Vue 3' }
  },
  [Language.UK]: {
    nav: { home: 'Головна', releases: 'Релізи', download: 'Завантажити', features: 'Можливості', terms: 'Умови', docs: 'Документація' },
    hero: { new_version: 'v2.0 Вже доступна', tagline: 'Розумний трекер активності', subtext: 'Приватний трекер активності. Розумійте, як ви витрачаєте час, завдяки детальній аналітиці та локальному зберіганню даних.', cta_download: 'Завантажити', cta_github: 'Вихідний код', built_for: 'Створено для швидкодії', powered_by: 'Працює на сучасних технологіях' },
    features: { title: 'Чому TimiGS?', realtime_title: 'Відстеження в реальному часі', realtime_desc: 'Автоматично виявляє активні вікна та відстежує тривалість їх використання.', privacy_title: 'Приватність перш за все', privacy_desc: 'Усі дані зберігаються локально в SQLite. Жодних хмарних завантажень.', analytics_title: 'Аналітика та графіки', analytics_desc: 'Візуалізуйте дані за допомогою красивих діаграм та графіків.', timeline_title: 'Хронологія', timeline_desc: 'Переглядайте історію активності день за днем з деталізацією.', crossplatform_title: 'Кросплатформеність', crossplatform_desc: 'Створено на Tauri v2 для високої продуктивності на Windows, Linux та macOS.', i18n_title: 'Багатомовність', i18n_desc: 'Повністю локалізований інтерфейс з підтримкою багатьох мов.' },
    downloads: { title: 'Завантажити TimiGS', subtitle: 'Оберіть версію для вашої операційної системи.', latest_version: 'Остання версія', windows: 'Windows', windows_desc: 'Нативні 64-бітні інсталятори для Windows 10 та 11. Оберіть .exe для стандартного встановлення.', mac: 'macOS', mac_desc: 'Оптимізовано для macOS. Підтримка процесорів Intel та Apple Silicon.', linux: 'Linux', linux_desc: 'Пакети для основних дистрибутивів. AppImage для сумісності, RPM для Fedora та DEB для Ubuntu.', source: 'Вихідний код', source_title: 'Вихідний код та інше', source_desc: 'Потрібен вихідний код, контрольні суми або старі версії? Відвідайте GitHub.', installer_label: 'Інсталятор', no_assets: 'Файли не знайдені.', loading: 'Завантаження...', error: 'Помилка завантаження.', no_assets_platform: 'Немає файлів для цієї платформи' },
    releases: { title: 'Примітки до випуску', subtitle: 'Досліджуйте розвиток TimiGS.', published_on: 'Опубліковано', view_on_github: 'Переглянути на GitHub', assets: 'Файли', latest_badge: 'ОСТАННІЙ РЕЛІЗ', prerelease_badge: 'Попередній реліз' },
    terms: { title: 'Умови та конфіденційність', privacy_title: 'Політика конфіденційності', privacy_content: 'TimiGS розроблено з урахуванням конфіденційності. Всі дані про вашу активність зберігаються виключно локально на вашому пристрої в базі даних SQLite. Ми не передаємо ваші особисті дані на зовнішні сервери.', data_title: 'Власність даних', data_content: 'Ви володієте своїми даними. Ви маєте повний контроль над експортом, видаленням або зміною вашої локальної бази даних у будь-який час.', license_title: 'Ліцензія', license_content: 'TimiGS - це програмне забезпечення з відкритим вихідним кодом, що надається за ліцензією MIT.' },
    footer: { rights: 'Всі права захищено.', created_by: 'Створено', built_with: 'Створено на Tauri, Rust та Vue 3' }
  },
  [Language.DE]: {
    nav: { home: 'Startseite', releases: 'Releases', download: 'Download', features: 'Funktionen', terms: 'AGB', docs: 'Doku' },
    hero: { new_version: 'v2.0 Jetzt verfügbar', tagline: 'Intelligenter Aktivitätstracker', subtext: 'Datenschutzorientiertes Aktivitäts-Tracking. Verstehen Sie mit detaillierten Analysen und rein lokaler Datenspeicherung, wie Sie Ihre Zeit verbringen.', cta_download: 'Jetzt laden', cta_github: 'Quellcode', built_for: 'Auf Leistung ausgelegt', powered_by: 'Angetrieben von modernen Technologien' },
    features: { title: 'Warum TimiGS?', realtime_title: 'Echtzeit-Tracking', realtime_desc: 'Erkennt automatisch aktive Fenster und erfasst die Nutzungsdauer.', privacy_title: 'Datenschutz zuerst', privacy_desc: 'Alle Daten werden lokal in SQLite gespeichert. Kein Cloud-Upload.', analytics_title: 'Analysen & Diagramme', analytics_desc: 'Visualisieren Sie Ihre Daten mit ansprechenden Donut-, Kreis- und Balkendiagrammen.', timeline_title: 'Zeitachsenansicht', timeline_desc: 'Durchsuchen Sie Ihren Aktivitätsverlauf Tag für Tag mit genauen Details.', crossplatform_title: 'Plattformübergreifend', crossplatform_desc: 'Basiert auf Tauri v2 für hohe Leistung unter Windows, Linux und macOS.', i18n_title: 'Mehrsprachig', i18n_desc: 'Vollständig lokalisierte Benutzeroberfläche mit Unterstützung für mehrere Sprachen.' },
    downloads: { title: 'TimiGS Herunterladen', subtitle: 'Wählen Sie die Version für Ihr Betriebssystem.', latest_version: 'Neueste Version', windows: 'Windows', windows_desc: 'Native 64-Bit-Installationsprogramme für Windows 10 und 11. Wählen Sie .exe für die Standardinstallation.', mac: 'macOS', mac_desc: 'Optimiert für macOS. Unterstützt Intel- und Apple Silicon-Chips.', linux: 'Linux', linux_desc: 'Pakete für gängige Distributionen. AppImage für Kompatibilität, RPM für Fedora, DEB für Ubuntu.', source: 'Quellcode', source_title: 'Quellcode & Assets', source_desc: 'Benötigen Sie Quellcode-Tarballs oder ältere Versionen? Besuchen Sie GitHub.', installer_label: 'Installer', no_assets: 'Keine Dateien gefunden.', loading: 'Laden...', error: 'Fehler beim Laden.', no_assets_platform: 'Keine Dateien für diese Plattform' },
    releases: { title: 'Versionshinweise', subtitle: 'Entdecken Sie die Entwicklung von TimiGS.', published_on: 'Veröffentlicht am', view_on_github: 'Auf GitHub ansehen', assets: 'Dateien', latest_badge: 'NEUESTE VERSION', prerelease_badge: 'Vorabversion' },
    terms: { title: 'AGB & Datenschutz', privacy_title: 'Datenschutzerklärung', privacy_content: 'TimiGS wurde mit Privatsphäre als Kernwert entwickelt. Alle gesammelten Daten werden lokal auf Ihrem Gerät in einer SQLite-Datenbank gespeichert. Wir übertragen keine persönlichen Daten an externe Server.', data_title: 'Datenbesitz', data_content: 'Sie besitzen Ihre Daten. Sie haben die volle Kontrolle darüber, Ihre lokale Datenbank jederzeit zu exportieren, zu löschen oder zu ändern.', license_title: 'Lizenz', license_content: 'TimiGS ist Open-Source-Software unter der MIT-Lizenz.' },
    footer: { rights: 'Alle Rechte vorbehalten.', created_by: 'Erstellt von', built_with: 'Erstellt mit Tauri, Rust & Vue 3' }
  },
  [Language.ZH_CN]: {
    nav: { home: '首页', releases: '版本', download: '下载', features: '功能', terms: '条款', docs: '文档' },
    hero: { new_version: 'v2.0 现已发布', tagline: '智能活动追踪器', subtext: '注重隐私的活动追踪。通过详细的分析和仅本地的数据存储，了解您如何花费时间。', cta_download: '立即下载', cta_github: '查看源码', built_for: '为性能而生', powered_by: '由现代技术驱动' },
    features: { title: '为什么选择 TimiGS？', realtime_title: '实时追踪', realtime_desc: '自动检测活动窗口并追踪使用时长。', privacy_title: '隐私至上', privacy_desc: '所有数据本地存储于 SQLite。绝不上传云端。', analytics_title: '分析与图表', analytics_desc: '通过精美的环形图、饼图和柱状图可视化数据。', timeline_title: '时间轴视图', timeline_desc: '逐日浏览详细的活动历史记录。', crossplatform_title: '跨平台', crossplatform_desc: '基于 Tauri v2 构建，在 Windows、Linux 和 macOS 上具有高性能。', i18n_title: '多语言', i18n_desc: '完全本地化的界面，支持多种全球语言。' },
    downloads: { title: '下载 TimiGS', subtitle: '选择适合您操作系统的版本。', latest_version: '最新版本', windows: 'Windows', windows_desc: '适用于 Windows 10 和 11 的原生 64 位安装程序。标准安装请选择 .exe。', mac: 'macOS', mac_desc: '针对 macOS 进行了优化。支持 Intel 和 Apple Silicon 芯片。', linux: 'Linux', linux_desc: '适用于主要发行版的软件包。AppImage 通用，RPM 适用于 Fedora，DEB 适用于 Ubuntu。', source: '源代码', source_title: '源代码及其他', source_desc: '需要源代码包、校验和或旧版本？请访问 GitHub 发布页面。', installer_label: '安装包', no_assets: '未找到文件。', loading: '加载中...', error: '加载失败。', no_assets_platform: '该平台暂无可用文件' },
    releases: { title: '发布说明', subtitle: '探索 TimiGS 的演变历程。', published_on: '发布于', view_on_github: '在 GitHub 查看', assets: '资源', latest_badge: '最新版本', prerelease_badge: '预发布' },
    terms: { title: '条款与隐私', privacy_title: '隐私政策', privacy_content: 'TimiGS 以隐私为核心。所有活动数据均存储在您设备的本地 SQLite 数据库中。我们不会将您的个人数据传输到任何外部云服务器。', data_title: '数据所有权', data_content: '您拥有您的数据。您可以随时导出、删除或修改您的本地数据库。', license_title: '许可证', license_content: 'TimiGS 是根据 MIT 许可证提供的开源软件。' },
    footer: { rights: '版权所有。', created_by: '创作者', built_with: '使用 Tauri, Rust & Vue 3 构建' }
  },
  [Language.ZH_TW]: {
    nav: { home: '首頁', releases: '版本', download: '下載', features: '功能', terms: '條款', docs: '文檔' },
    hero: { new_version: 'v2.0 現已發布', tagline: '智能活動追蹤器', subtext: '注重隱私的活動追蹤。透過詳細的分析和僅本地的數據存儲，了解您如何花費時間。', cta_download: '立即下載', cta_github: '查看源碼', built_for: '為性能而生', powered_by: '由現代技術驅動' },
    features: { title: '為什麼選擇 TimiGS？', realtime_title: '即時追蹤', realtime_desc: '自動檢測活動視窗並追蹤使用時長。', privacy_title: '隱私至上', privacy_desc: '所有數據本地存儲於 SQLite。絕不上傳雲端。', analytics_title: '分析與圖表', analytics_desc: '透過精美的環形圖、圓餅圖和柱狀圖可視化數據。', timeline_title: '時間軸視圖', timeline_desc: '逐日瀏覽詳細的活動歷史記錄。', crossplatform_title: '跨平台', crossplatform_desc: '基於 Tauri v2 構建，在 Windows、Linux 和 macOS 上具有高性能。', i18n_title: '多語言', i18n_desc: '完全本地化的介面，支持多種全球語言。' },
    downloads: { title: '下載 TimiGS', subtitle: '選擇適合您操作系統的版本。', latest_version: '最新版本', windows: 'Windows', windows_desc: '適用於 Windows 10 和 11 的原生 64 位安裝程式。標準安裝請選擇 .exe。', mac: 'macOS', mac_desc: '針對 macOS 進行了優化。支持 Intel 和 Apple Silicon 晶片。', linux: 'Linux', linux_desc: '適用於主要發行版的軟件包。AppImage 通用，RPM 適用於 Fedora，DEB 適用於 Ubuntu。', source: '源代碼', source_title: '源代碼及其他', source_desc: '需要源代碼包、校驗和或舊版本？請訪問 GitHub 發布頁面。', installer_label: '安裝程式', no_assets: '未找到文件。', loading: '加載中...', error: '加載失敗。', no_assets_platform: '該平台暫無可用文件' },
    releases: { title: '發布說明', subtitle: '探索 TimiGS 的演變歷程。', published_on: '發布於', view_on_github: '在 GitHub 查看', assets: '資源', latest_badge: '最新版本', prerelease_badge: '預發布' },
    terms: { title: '條款與隱私', privacy_title: '隱私政策', privacy_content: 'TimiGS 以隱私為核心。所有活動數據均存儲在您設備的本地 SQLite 數據庫中。我們不會將您的個人數據傳輸到任何外部雲服務器。', data_title: '數據所有權', data_content: '您擁有您的數據。您可以隨時導出、刪除或修改您的本地數據庫。', license_title: '許可證', license_content: 'TimiGS 是根據 MIT 許可證提供的開源軟件。' },
    footer: { rights: '版權所有。', created_by: '創作者', built_with: '使用 Tauri, Rust & Vue 3 構建' }
  },
  [Language.ES]: {
    nav: { home: 'Inicio', releases: 'Versiones', download: 'Descargar', features: 'Características', terms: 'Términos', docs: 'Docs' },
    hero: { new_version: 'v2.0 Ya disponible', tagline: 'Rastreador de Actividad Inteligente', subtext: 'Seguimiento de actividad centrado en la privacidad. Entienda cómo gasta su tiempo con análisis detallados y almacenamiento de datos exclusivamente local.', cta_download: 'Descargar', cta_github: 'Código Fuente', built_for: 'Construido para rendimiento', powered_by: 'Impulsado por tecnologías modernas' },
    features: { title: '¿Por qué TimiGS?', realtime_title: 'Rastreo en tiempo real', realtime_desc: 'Detecta automáticamente las ventanas activas y rastrea la duración del uso.', privacy_title: 'Privacidad primero', privacy_desc: 'Todos los datos se almacenan localmente en SQLite. Sin subidas a la nube.', analytics_title: 'Análisis y gráficos', analytics_desc: 'Visualiza tus datos con hermosos gráficos de donas, pasteles y barras.', timeline_title: 'Línea de tiempo', timeline_desc: 'Navega por tu historial de actividad día a día con detalles granulares.', crossplatform_title: 'Multiplataforma', crossplatform_desc: 'Construido con Tauri v2 para un alto rendimiento en Windows, Linux y macOS.', i18n_title: 'Multilingüe', i18n_desc: 'Interfaz totalmente localizada que soporta múltiples idiomas globales.' },
    downloads: { title: 'Descargar TimiGS', subtitle: 'Elige la versión para tu sistema operativo.', latest_version: 'Última versión', windows: 'Windows', windows_desc: 'Instaladores nativos de 64 bits para Windows 10 y 11. Elige .exe para instalación estándar.', mac: 'macOS', mac_desc: 'Optimizado para macOS. Soporta chips Intel y Apple Silicon mediante binarios universales.', linux: 'Linux', linux_desc: 'Paquetes para las principales distribuciones. AppImage para compatibilidad universal, RPM para Fedora y DEB para Ubuntu/Debian.', source: 'Código Fuente', source_title: 'Código Fuente y Otros', source_desc: '¿Necesitas código fuente o versiones anteriores? Visita GitHub.', installer_label: 'Instalador', no_assets: 'No se encontraron archivos.', loading: 'Cargando versiones...', error: 'Error al cargar versiones.', no_assets_platform: 'No hay archivos para esta plataforma' },
    releases: { title: 'Notas de la versión', subtitle: 'Explora la evolución de TimiGS.', published_on: 'Publicado el', view_on_github: 'Ver en GitHub', assets: 'Archivos', latest_badge: 'ÚLTIMA VERSIÓN', prerelease_badge: 'Pre-lanzamiento' },
    terms: { title: 'Términos y Privacidad', privacy_title: 'Política de Privacidad', privacy_content: 'TimiGS está diseñado con la privacidad como valor central. Todos los datos se almacenan estrictamente de forma local en su dispositivo utilizando una base de datos SQLite. No transmitimos sus datos personales a servidores externos.', data_title: 'Propiedad de los datos', data_content: 'Usted es dueño de sus datos. Tiene control total para exportar, eliminar o modificar su base de datos local en cualquier momento.', license_title: 'Licencia', license_content: 'TimiGS es software de código abierto proporcionado bajo la licencia MIT.' },
    footer: { rights: 'Todos los derechos reservados.', created_by: 'Creado por', built_with: 'Hecho con Tauri, Rust y Vue 3' }
  },
  [Language.FR]: {
    nav: { home: 'Accueil', releases: 'Versions', download: 'Télécharger', features: 'Fonctionnalités', terms: 'Conditions', docs: 'Docs' },
    hero: { new_version: 'v2.0 Maintenant disponible', tagline: 'Suivi d\'activité intelligent', subtext: 'Suivi d\'activité axé sur la confidentialité. Comprenez comment vous passez votre temps grâce à des analyses détaillées et un stockage de données uniquement local.', cta_download: 'Télécharger', cta_github: 'Code Source', built_for: 'Conçu pour la performance', powered_by: 'Propulsé par des technologies modernes' },
    features: { title: 'Pourquoi TimiGS ?', realtime_title: 'Suivi en temps réel', realtime_desc: 'Détecte automatiquement les fenêtres actives et suit la durée d\'utilisation.', privacy_title: 'Confidentialité d\'abord', privacy_desc: 'Toutes les données sont stockées localement dans SQLite. Aucun envoi vers le cloud.', analytics_title: 'Analyses et graphiques', analytics_desc: 'Visualisez vos données avec de beaux graphiques en beignet, camembert et barres.', timeline_title: 'Chronologie', timeline_desc: 'Parcourez votre historique d\'activité jour par jour avec des détails précis.', crossplatform_title: 'Multiplateforme', crossplatform_desc: 'Construit avec Tauri v2 pour des performances élevées sur Windows, Linux et macOS.', i18n_title: 'Multilingue', i18n_desc: 'Interface entièrement localisée prenant en charge plusieurs langues.' },
    downloads: { title: 'Télécharger TimiGS', subtitle: 'Choisissez la version pour votre système d\'exploitation.', latest_version: 'Dernière version', windows: 'Windows', windows_desc: 'Installateurs natifs 64 bits pour Windows 10 et 11. Choisissez .exe pour une installation standard.', mac: 'macOS', mac_desc: 'Optimisé pour macOS. Prend en charge les puces Intel et Apple Silicon.', linux: 'Linux', linux_desc: 'Paquets pour les principales distributions. AppImage pour la compatibilité, RPM pour Fedora et DEB pour Ubuntu.', source: 'Code Source', source_title: 'Code Source et autres', source_desc: 'Besoin du code source ou d\'anciennes versions ? Visitez GitHub.', installer_label: 'Installateur', no_assets: 'Aucun fichier trouvé.', loading: 'Chargement...', error: 'Erreur de chargement.', no_assets_platform: 'Aucun fichier pour cette plateforme' },
    releases: { title: 'Notes de version', subtitle: 'Explorez l\'évolution de TimiGS.', published_on: 'Publié le', view_on_github: 'Voir sur GitHub', assets: 'Fichiers', latest_badge: 'DERNIÈRE VERSION', prerelease_badge: 'Pré-version' },
    terms: { title: 'Conditions et Confidentialité', privacy_title: 'Politique de Confidentialité', privacy_content: 'TimiGS est conçu avec la confidentialité comme valeur fondamentale. Toutes les données sont stockées localement sur votre appareil dans une base de données SQLite. Nous ne transmettons aucune donnée personnelle à des serveurs externes.', data_title: 'Propriété des données', data_content: 'Vous êtes propriétaire de vos données. Vous avez le contrôle total pour exporter, supprimer ou modifier votre base de données locale à tout moment.', license_title: 'Licence', license_content: 'TimiGS est un logiciel open source fourni sous la licence MIT.' },
    footer: { rights: 'Tous droits réservés.', created_by: 'Créé par', built_with: 'Fait avec Tauri, Rust et Vue 3' }
  },
  [Language.AR]: {
    nav: { home: 'الرئيسية', releases: 'الإصدارات', download: 'تحميل', features: 'الميزات', terms: 'الشروط', docs: 'وثائق' },
    hero: { new_version: 'الإصدار 2.0 متاح الآن', tagline: 'متتبع النشاط الذكي', subtext: 'تتبع النشاط مع التركيز على الخصوصية. افهم كيف تقضي وقتك من خلال تحليلات تفصيلية وتخزين البيانات محليًا فقط.', cta_download: 'تحميل الآن', cta_github: 'عرض المصدر', built_for: 'بنيت للأداء', powered_by: 'مدعوم بتقنيات حديثة' },
    features: { title: 'لماذا TimiGS؟', realtime_title: 'تتبع في الوقت الحقيقي', realtime_desc: 'يكتشف النوافذ النشطة تلقائيًا ويتتبع مدة الاستخدام.', privacy_title: 'الخصوصية أولاً', privacy_desc: 'يتم تخزين جميع البيانات محليًا في SQLite. لا يوجد تحميل سحابي.', analytics_title: 'التحليلات والرسوم البيانية', analytics_desc: 'تصور البيانات برسوم بيانية دائرية وشريطية جميلة.', timeline_title: 'الجدول الزمني', timeline_desc: 'تصفح سجل النشاط يومًا بعد يوم بتفاصيل دقيقة.', crossplatform_title: 'متعدد المنصات', crossplatform_desc: 'مبني باستخدام Tauri v2 لأداء عالٍ على Windows و Linux و macOS.', i18n_title: 'متعدد اللغات', i18n_desc: 'واجهة مترجمة بالكامل تدعم لغات عالمية متعددة.' },
    downloads: { title: 'تحميل TimiGS', subtitle: 'اختر الإصدار المناسب لنظام التشغيل الخاص بك.', latest_version: 'أحدث إصدار', windows: 'Windows', windows_desc: 'مثبتات أصلية 64 بت لنظامي التشغيل Windows 10 و 11. اختر .exe للتثبيت القياسي.', mac: 'macOS', mac_desc: 'محسن لنظام macOS. يدعم معالجات Intel و Apple Silicon.', linux: 'Linux', linux_desc: 'حزم للتوزيعات الرئيسية. AppImage للتوافق العالمي، RPM لـ Fedora، و DEB لـ Ubuntu.', source: 'مصدر الكود', source_title: 'كود المصدر وملفات أخرى', source_desc: 'هل تحتاج إلى كود المصدر أو إصدارات أقدم؟ قم بزيارة GitHub.', installer_label: 'مثبت', no_assets: 'لا توجد ملفات.', loading: 'جار التحميل...', error: 'فشل التحميل.', no_assets_platform: 'لا توجد ملفات لهذه المنصة' },
    releases: { title: 'ملاحظات الإصدار', subtitle: 'استكشف تطور TimiGS.', published_on: 'نشر في', view_on_github: 'عرض على GitHub', assets: 'الملفات', latest_badge: 'أحدث إصدار', prerelease_badge: 'نسخة أولية' },
    terms: { title: 'الشروط والخصوصية', privacy_title: 'سياسة الخصوصية', privacy_content: 'تم تصميم TimiGS مع الخصوصية كقيمة أساسية. يتم تخزين جميع البيانات محليًا على جهازك باستخدام قاعدة بيانات SQLite. نحن لا ننقل بياناتك الشخصية إلى خوادم خارجية.', data_title: 'ملكية البيانات', data_content: 'أنت تملك بياناتك. لديك السيطرة الكاملة لتصدير أو حذف أو تعديل قاعدة البيانات المحلية الخاصة بك في أي وقت.', license_title: 'الترخيص', license_content: 'TimiGS هو برنامج مفتوح المصدر مقدم بموجب ترخيص MIT.' },
    footer: { rights: 'جميع الحقوق محفوظة.', created_by: 'تم إنشاؤه بواسطة', built_with: 'بنيت مع Tauri, Rust و Vue 3' }
  },
  [Language.NL]: {
    nav: { home: 'Home', releases: 'Versies', download: 'Downloaden', features: 'Functies', terms: 'Voorwaarden', docs: 'Docs' },
    hero: { new_version: 'v2.0 Nu Beschikbaar', tagline: 'Intelligente Activiteitstracker', subtext: 'Privacy-gerichte activiteitentracking. Begrijp hoe u uw tijd besteedt met gedetailleerde analyses en alleen lokale gegevensopslag.', cta_download: 'Download Nu', cta_github: 'Bekijk Broncode', built_for: 'Gebouwd voor Prestaties', powered_by: 'Aangedreven door Moderne Technologieën' },
    features: { title: 'Waarom TimiGS?', realtime_title: 'Real-time Tracking', realtime_desc: 'Detecteert automatisch actieve vensters en houdt de gebruiksduur bij.', privacy_title: 'Privacy Eerst', privacy_desc: 'Alle data wordt lokaal opgeslagen in SQLite. Geen cloud uploads.', analytics_title: 'Analytics & Grafieken', analytics_desc: 'Visualiseer data met prachtige ring-, cirkel- en staafdiagrammen.', timeline_title: 'Tijdlijn Weergave', timeline_desc: 'Bekijk uw activiteitsgeschiedenis dag per dag met granulaire details.', crossplatform_title: 'Cross-platform', crossplatform_desc: 'Gebouwd met Tauri v2 voor hoge prestaties op Windows, Linux en macOS.', i18n_title: 'Meertalig', i18n_desc: 'Volledig gelokaliseerde interface met ondersteuning voor meerdere talen.' },
    downloads: { title: 'TimiGS Downloaden', subtitle: 'Kies de versie voor uw besturingssysteem.', latest_version: 'Laatste Versie', windows: 'Windows', windows_desc: 'Native 64-bit installers voor Windows 10 en 11. Kies .exe voor standaard installatie.', mac: 'macOS', mac_desc: 'Geoptimaliseerd voor macOS. Ondersteunt Intel en Apple Silicon chips.', linux: 'Linux', linux_desc: 'Pakketten voor grote distributies. AppImage voor universele compatibiliteit, RPM voor Fedora, DEB voor Ubuntu.', source: 'Broncode', source_title: 'Broncode & Andere', source_desc: 'Toegang nodig tot broncode of oudere versies? Bezoek GitHub.', installer_label: 'Installer', no_assets: 'Geen bestanden gevonden.', loading: 'Versies laden...', error: 'Fout bij laden.', no_assets_platform: 'Geen bestanden voor dit platform' },
    releases: { title: 'Release Notes', subtitle: 'Ontdek de evolutie van TimiGS.', published_on: 'Gepubliceerd op', view_on_github: 'Bekijk op GitHub', assets: 'Bestanden', latest_badge: 'LAATSTE VERSIE', prerelease_badge: 'Pre-release' },
    terms: { title: 'Voorwaarden & Privacy', privacy_title: 'Privacybeleid', privacy_content: 'TimiGS is ontworpen met privacy als kernwaarde. Alle verzamelde gegevens worden lokaal op uw apparaat opgeslagen met behulp van een SQLite-database. We sturen geen persoonlijke gegevens naar externe servers.', data_title: 'Gegevensbezit', data_content: 'U bezit uw gegevens. U heeft volledige controle om uw lokale database op elk moment te exporteren, verwijderen of wijzigen.', license_title: 'Licentie', license_content: 'TimiGS is open-source software onder de MIT-licentie.' },
    footer: { rights: 'Alle rechten voorbehouden.', created_by: 'Gemaakt door', built_with: 'Gebouwd met Tauri, Rust & Vue 3' }
  },
  [Language.BE]: {
    nav: { home: 'Галоўная', releases: 'Рэлізы', download: 'Спампаваць', features: 'Магчымасці', terms: 'Умовы', docs: 'Дакументацыя' },
    hero: { new_version: 'v2.0 Ужо даступна', tagline: 'Разумны трэкер актыўнасці', subtext: 'Трэкер актыўнасці з акцэнтам на прыватнасць. Зразумейце, як вы бавіце час, дзякуючы дэталёвай аналітыцы і лакальнаму захаванню дадзеных.', cta_download: 'Спампаваць', cta_github: 'Зыходны код', built_for: 'Створана для хуткасці', powered_by: 'Працуе на сучасных тэхналогіях' },
    features: { title: 'Чаму TimiGS?', realtime_title: 'Адсочванне ў рэальным часе', realtime_desc: 'Аўтаматычна выяўляе актыўныя вокны і адсочвае працягласць іх выкарыстання.', privacy_title: 'Прыватнасць перш за ўсё', privacy_desc: 'Усе дадзеныя захоўваюцца лакальна ў SQLite. Ніякіх хмарных загрузак.', analytics_title: 'Аналітыка і графікі', analytics_desc: 'Візуалізуйце дадзеныя з дапамогай прыгожых дыяграм і графікаў.', timeline_title: 'Храналогія', timeline_desc: 'Праглядайце гісторыю актыўнасці дзень за днём з дэталізацыяй.', crossplatform_title: 'Кросплатформавасць', crossplatform_desc: 'Створана на Tauri v2 для высокай прадукцыйнасці на Windows, Linux і macOS.', i18n_title: 'Шматмоўнасць', i18n_desc: 'Цалкам лакалізаваны інтэрфейс з падтрымкай многіх моў.' },
    downloads: { title: 'Спампаваць TimiGS', subtitle: 'Абярыце версію для вашай аперацыйнай сістэмы.', latest_version: 'Апошняя версія', windows: 'Windows', windows_desc: 'Натыўныя 64-бітныя ўсталёўшчыкі для Windows 10 і 11. Абярыце .exe для стандартнай усталёўкі.', mac: 'macOS', mac_desc: 'Аптымізавана для macOS. Падтрымка працэсараў Intel і Apple Silicon.', linux: 'Linux', linux_desc: 'Пакеты для асноўных дыстрыбутываў. AppImage для сумяшчальнасці, RPM для Fedora і DEB для Ubuntu.', source: 'Зыходны код', source_title: 'Зыходны код і іншае', source_desc: 'Патрэбен зыходны код або старыя версіі? Наведайце GitHub.', installer_label: 'Усталёўшчык', no_assets: 'Файлы не знойдзены.', loading: 'Загрузка...', error: 'Памылка загрузкі.', no_assets_platform: 'Няма файлаў для гэтай платформы' },
    releases: { title: 'Нататкі да выпуску', subtitle: 'Даследуйце развіццё TimiGS.', published_on: 'Апублікавана', view_on_github: 'Глядзець на GitHub', assets: 'Файлы', latest_badge: 'АПОШНІ РЭЛІЗ', prerelease_badge: 'Папярэдні рэліз' },
    terms: { title: 'Умовы і прыватнасць', privacy_title: 'Палітыка прыватнасці', privacy_content: 'TimiGS распрацаваны з улікам прыватнасці. Усе дадзеныя захоўваюцца лакальна на вашай прыладзе ў базе дадзеных SQLite. Мы не перадаем вашы асабістыя дадзеныя на знешнія серверы.', data_title: 'Уласнасць дадзеных', data_content: 'Вы валодаеце сваімі дадзенымі. Вы маеце поўны кантроль над экспартам, выдаленнем або змяненнем вашай лакальнай базы дадзеных у любы час.', license_title: 'Ліцэнзія', license_content: 'TimiGS - гэта праграмнае забеспячэнне з адкрытым зыходным кодам пад ліцэнзіяй MIT.' },
    footer: { rights: 'Усе правы абаронены.', created_by: 'Створана', built_with: 'Створана на Tauri, Rust і Vue 3' }
  },
};